id: ADD92DB79
title: The Indestructible Vajra Garland, An Aspiration Prayer for the Lives of the
  Supreme Holders of the Non-Sectarian Teachings
type: translation
pechas:
- I9CC4C925
- IA0E16DCA
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:00:19.467348
  last_modified_at: 2023-01-04 12:00:19.467364
  collections:
  - Jamgön Kongtrul Lodrö Thaye Series
  - Works of Tibetan Masters
alignment_to_base:
  I9CC4C925/886D: '5585'
  IA0E16DCA/4844: '5585'
